#!/bin/sh

name="bin"
target="${HOME}/.local/${name}"

if [ ! -d "${target}" ]; then
	mkdir "${target}"
fi

case "${1}" in
    -d|--delete|del|delete|d|rm)
        find ${target} -type l -exec unlink {} \;
        ;;
    *)
        for bin in $name/*; do
            printf 'stow: %s -> %s\n' $bin $target
        done
        stow "${name}" -t "${target}" $@
        ;;
esac

